import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { GlobalProvider } from "@/provider/GlobalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Copy to clipboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
